name: "Ancientdash"
description: "Dashboard for old web browsers"
version: "1.0.5"
slug: "ancientdash"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
ports:
  5000/tcp: 5000
homeassistant_api: true
#webui: "http://[HOST]:[PORT:5000]"
ingress: true
ingress_port: 5000
